name: Deploy preview

on:
  release:
    types: [published, created, edited]

jobs:

  cdn:
    name: Qiniu CDN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1

    - name: Download qshell
      run: |
        wget http://devtools.qiniu.com/qshell-linux-x86-v2.4.0.zip
        unzip qshell-linux-x86-v2.4.0.zip
        mv qshell-linux-x86-v2.4.0 qshell
    - name: CDN login
      run: ./qshell account ${{ secrets.AK }} ${{ secrets.SK }} GITHUB_ACTION

    - name: Set env
      run: |
        echo "BASE_URL=/d2-advance/preview/" > .env.local
    - name: Check lint
      run: yarn lint:strict
    - name: Check unit test
      run: yarn test:unit
    - name: Build
      run: yarn build

    - name: CDN upload
      run: |
        QINIU_BUCKET='d2-cdn'
        DIST_FOLDER='/dist'
        PATH_SUFFIX='/preview'
        REPO=${GITHUB_REPOSITORY//*\//}
        ./qshell qupload2 \
        --src-dir=$GITHUB_WORKSPACE$DIST_FOLDER \
        --bucket=$QINIU_BUCKET \
        --key-prefix=$REPO$PATH_SUFFIX/ \
        --overwrite=true \
        --check-exists=true \
        --check-hash=true \
        --check-size=true \
        --rescan-local=true \
        --thread-count=32
    - name: CDN refresh
      run: |
        SITE='https://cdn.d2.pub/'
        REFRESH_URL=$SITE$REPO$PATH_SUFFIX/
        echo $REFRESH_URL > cdnrefresh.txt
        ./qshell cdnrefresh --dirs -i ./cdnrefresh.txt

  ftp:
    name: D2 FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1

    - name: Set env
      run: |
        echo "BASE_URL=/d2-advance/preview/" > .env.local
    - name: Check lint
      run: yarn lint:strict
    - name: Check unit test
      run: yarn test:unit
    - name: Build
      run: yarn build

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: dist
        REMOTE_DIR: /www/d2-advance/preview
        ARGS: --delete --verbose --parallel=100

  gh-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1

    - name: Set env
      run: |
        echo "BASE_URL=/d2-advance/" > .env.local
    - name: Check lint
      run: yarn lint:strict
    - name: Check unit test
      run: yarn test:unit
    - name: Build
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        forceOrphan: true
